GET http://localhost:5134/books
###
GET http://localhost:5134/books/13
###
POST http://localhost:5134/books/
Content-Type: application/json

{
    "name": "Zero to One",
    "genre": "Business and entrepreneurship",
    "price": 19.22,
    "releaseDate": "2014-09-16"
}
###
PUT http://localhost:5134/books/12
Content-Type: application/json

{
    "name": "F*S",
    "genre": "Business and revolution",
    "price": 0.22,
    "releaseDate": "1911-09-17"
}
###
DELETE http://localhost:5134/books/3