GET http://localhost:5134/books
###
GET http://localhost:5134/books/3
###
POST http://localhost:5134/books/
Content-Type: application/json

{
    "name": "Zero to One",
    "genre": "Business and entrepreneurship",
    "price": 19.22,
    "releaseDate": "2014-09-16"
}

